version: "3.9"

services:
  loggenerator:
    build:
      context: ../BACKEND/loggenerator
      dockerfile: Dockerfile
    image: loggenerator:latest
    container_name: loggenerator
    ports:
      - "8780:8780"
    volumes:
      - shared-logs:/root/log
    networks:
      - lognet

  loglistener:
    build:
      context: ../BACKEND/loglistener
      dockerfile: Dockerfile
    image: loglistener:latest
    container_name: loglistener
    ports:
      - "8785:8785"
    depends_on:
      - loggenerator
    volumes:
      - shared-logs:/root/log
    networks:
      - lognet

volumes:
  shared-logs:                          # declare named volume

networks:
  lognet:
    driver: bridge
