version: "3.8"

services:
  frontend:
    image: srini341/log-processing-frontend:latest
    container_name: log-processing-frontend-${BUILD_NUMBER}
    ports:
      - "3001:3000"
    restart: always
