pipeline {
    agent any

    environment {
        APP_NAME = 'frontend-reactjs'
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
    }

    stages {
        stage('Checkout') {
            steps {
                // Clone your repo containing ReactJS and docker-compose.yml
                git 'https://github.com/vivekgshan/Log-Processing.git'
            }
        }
        stage('Build') {
            steps {
                // Build ReactJS app
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Docker Compose Up') {
            steps {
                // Deploy using Docker Compose
                sh "docker-compose -f ${DOCKER_COMPOSE_FILE} up -d --build"
            }
        }
    }
    post {
        always {
            echo "Deployment stage completed"
        }
    }
}
