pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "log-processing-ui"
        DOCKER_TAG = "latest"
        CONTAINER_NAME = "log-processing-ui"
        HOST_PORT = "3000"
        CONTAINER_PORT = "80"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev',
                    url: 'https://github.com/vivekgshan/Log-Processing.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('FRONTEND') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh """
                    echo "🔍 Running Trivy vulnerability scan..."
        
                    # Basic scan
                    trivy image ${DOCKER_IMAGE}:${DOCKER_TAG}
        
                    # Fail pipeline if CRITICAL vulnerabilities are found
                    trivy image --exit-code 1 --severity CRITICAL ${DOCKER_IMAGE}:${DOCKER_TAG}
        
                    # Save detailed report
                    trivy image --format table --output trivy-report.txt ${DOCKER_IMAGE}:${DOCKER_TAG}
                """
            }
        }
       
        stage('Deploy to EC2') {
            steps {
                script {
                    sh """
                        echo "Stopping old container if running..."
                        docker rm -f ${CONTAINER_NAME} || true

                        echo "Starting new container..."
                        docker run -d -p ${HOST_PORT}:${CONTAINER_PORT} --name ${CONTAINER_NAME} ${DOCKER_IMAGE}:${DOCKER_TAG}
                    """
                }
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful! UI is live at http://<EC2-Public-IP>:${HOST_PORT}"
        }
        failure {
            echo "❌ Deployment failed. Check Jenkins logs."
        }
        always {
            archiveArtifacts artifacts: 'trivy-report.txt', fingerprint: true
       }
    }
}
