name: Log Collector CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Run Unit Tests
      run: mvn test

    - name: Build Docker Image
      run: docker build -t srini341/log-collector:latest .

    - name: Run Health Check
      run: |
        docker run -d -p 8080:8080 --name log-check srini341/log-collector:latest
        sleep 20
        curl --fail http://localhost:8080/actuator/health

    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push srini341/log-collector:latest
