version: "3.8"

services:

  db:
    image: postgres:15-alpine
    container_name: log-processing-postgres
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lognet
    restart: always

  loglistenercollector:
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/loglistenercollector:${IMAGE_TAG}
    container_name: loglistenercollector
    ports:
      - "8785:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    volumes:
      - ./shared_logs:/app/logs
    depends_on:
      - db
    networks:
      - lognet
    restart: always

  loginfopersistor:
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/loginfopersistor:${IMAGE_TAG}
    container_name: loginfopersistor
    ports:
      - "8783:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - db
    networks:
      - lognet
    restart: always

  logwarnpersistor:
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/logwarnpersistor:${IMAGE_TAG}
    container_name: logwarnpersistor
    ports:
      - "8784:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - db
    networks:
      - lognet
    restart: always

  logdebugpersistor:
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/logdebugpersistor:${IMAGE_TAG}
    container_name: logdebugpersistor
    ports:
      - "8781:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - db
    networks:
      - lognet
    restart: always

  logerrorpersistor:
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/logerrorpersistor:${IMAGE_TAG}
    container_name: logerrorpersistor
    ports:
      - "8782:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - db
    networks:
      - lognet
    restart: always

  frontend:
    image: ${ECR_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:${IMAGE_TAG}
    container_name: log-processing-frontend
    ports:
      - "3001:80"
    depends_on:
      - loglistenercollector
      - loginfopersistor
      - logwarnpersistor
      - logdebugpersistor
      - logerrorpersistor
    networks:
      - lognet
    restart: always

volumes:
  pgdata:
  shared_logs:

networks:
  lognet:
    driver: bridge
