version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  loganalyser:
    build: ./loganalyser
    container_name: loganalyser
    image: mudam5/loganalyser:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - postgres
    ports:
      - "8081:8080"

  logcollector:
    build: ./logcollector
    container_name: logcollector
    image: mudam5/logcollector:latest
    ports:
      - "8082:8080"

  logdebugpersistor:
    build: ./logdebugpersistor
    container_name: logdebugpersistor
    image: mudam5/logdebugpersistor:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - postgres
    ports:
      - "8083:8080"

  logerrorpersistor:
    build: ./logerrorpersistor
    container_name: logerrorpersistor
    image: mudam5/logerrorpersistor:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - postgres
    ports:
      - "8084:8080"

  loginfopersistor:
    build: ./loginfopersistor
    container_name: loginfopersistor
    image: mudam5/loginfopersistor:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - postgres
    ports:
      - "8085:8080"

  logwarnpersistor:
    build: ./logwarnpersistor
    container_name: logwarnpersistor
    image: mudam5/logwarnpersistor:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/logdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tiger
    depends_on:
      - postgres
    ports:
      - "8086:8080"

  loglistener:
    build: ./loglistener
    container_name: loglistener
    image: mudam5/loglistener:latest
    ports:
      - "8087:8080"

  loglistenercollector:
    build: ./loglistenercollector
    container_name: loglistenercollector
    image: mudam5/loglistenercollector:latest
    ports:
      - "8088:8080"

  loggenerator:
    build: ./loggenerator
    container_name: loggenerator
    image: mudam5/loggenerator:latest
    ports:
      - "8089:8080"

volumes:
  postgres_data:
