services:

  logcreator:
    ports:
      - "9096:9096"
    environment:
      server.port: 9096
    # other configs

  loggenerator:
    ports:
      - "8780:8780"
    environment:
      server.port: 8780
    # other configs

  loglistenercollector:
    ports:
      - "8785:8785"
    environment:
      server.port: 8785
    # other configs

  loginfopersistor:
    ports:
      - "8783:8783"
    environment:
      server.port: 8783
    # other configs

  logwarnpersistor:
    ports:
      - "8784:8784"
    environment:
      server.port: 8784
    # other configs

  logdebugpersistor:
    ports:
      - "8781:8781"
    environment:
      server.port: 8781
    # other configs

  logerrorpersistor:
    ports:
      - "8782:8782"
    environment:
      server.port: 8782
    # other configs

  loganalyser:
    ports:
      - "8086:8086"
    environment:
      server.port: 8086
    # other configs

  logexport:
    ports:
      - "9097:9097"
    environment:
      server.port: 9097
    # other configs
