version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"    # maps container port 3000 to host port 3000
    depends_on:
      - backend         # frontend depends on backend being up
    environment:
      - REACT_APP_API_URL=http://backend:5000  # example environment variable

  backend:
    build: ./backend
    ports:
      - "5000:5000"    # maps container port 5000 to host port 5000
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb  # example env var
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

