version: "3.8"

services:
  backend:
    image: vivekgshan/log-processing-backend:latest
    container_name: log-processing-backend
    ports:
      - "8081:8080"
    restart: always

  frontend:
    image: vivekgshan/log-processing-frontend:latest
    container_name: log-processing-frontend
    ports:
      - "3001:3000"
    restart: always
