global:
  scrape_interval: 5s   # How often to scrape metrics
  evaluation_interval: 5s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Scrape Spring Boot apps (Actuator Prometheus endpoint)
  - job_name: 'spring-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'logcollector:8789'
          - 'logerrorpersistor:8782'
          - 'logdebugpersistor:8781'
          - 'logwarnpersistor:8784'
          - 'loginfopersistor:8783'
          - 'loganalyser:8086'
