{
 "title": "Log generator and listener Dashboard",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "LogGenerator Logs (Table)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"loggenerator\"}"
    }
   ]
  },
  {
   "title": "LogGenerator Log Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count_over_time({job=\"loggenerator\"}[1m])"
    }
   ]
  },
  {
   "title": "LogGenerator Log Levels",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"loggenerator\"}[5m]))\r\n"
    }
   ]
  },
  {
   "title": "LogListener Logs (Table)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"loglistener\"}"
    }
   ]
  },
  {
   "title": "LogListener Log Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count_over_time({job=\"loglistener\"}[1m])"
    }
   ]
  },
  {
   "title": "LogListener Log Levels",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({job=\"loglistener\"}[5m]))\r\n"
    }
   ]
  }
 ]
}